version: '3.7'

services:
    webapp-server:
      build:
        context: .
        dockerfile: Dockerfile
      image: myapp-server-img
      container_name: myapp-node-express
      volumes:
       - .:/usr/src/app
       - /usr/src/app/node_modules
      ports:
        - "8000:8000"
      depends_on:
        - mongo
      env_file: .env
      environment:
        - PORT=$PORT
        - MONGO_URI=$MONGO_URI
       
    mongo:
      image: mongo
      container_name: myapp-mongodb
      ports:
        - "27017:27017"